### PR TITLE
Footer work

### PR DESCRIPTION
**Pull request by tcarrio**
Test this to see if the CSS is working

### CODE REVIEW

**Comment by jccalver** [comment]
still isn't working

**Comment by tcarrio** [comment]
Are you using the web preview on Brackets? 

The CSS/JS links are all based off the folder structure. If you simply open the webpages it won't have the correct folder structure to call the linked files. 

New link relations:

``` html
<link href="/css/bootstrap.css" rel="stylesheet">
<script src="/js/cpnamefiller.js"></script>
```

Rather than 

``` html
<link href="css/bootstrap.css" rel="stylesheet">
<script src="js/cpnamefiller.js"></script>
```

Since the files will be under the root css/js folders on the server side web container.

**Comment by tcarrio** [comment]
I did a complete folder deletion and recloned the repo to check, still worked fine on mine. If it could be that we should merge to check on the http://nssn.carrio.me domain

**Comment by jccalver** [comment]
yeah, with live preview, the CSS doesn't work.
Works perfectly on your server

**Comment by jccalver** [comment]
scratch that, it works as expected!

**Pull request merged**
